version: '2'

services:
  # Reverse proxy
  reverse_proxy:
    image: jwilder/nginx-proxy:latest
    ports:
        - "80:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    networks:
      - webstack

  checkfood:
    build: .
    ports:
      - "8000:80"
    environment:
      VIRTUAL_HOST: checkfood.dev
    volumes:
      - .:/var/www
    links:
      - postgres
    networks:
      - webstack

  postgres:
    image: postgres:9.5
    ports:
        - "5432"
    environment:
        POSTGRES_USER: checkfood
        POSTGRES_PASSWORD: checkfood
        PGPASSWORD: checkfood
        PGDATA: /var/lib/postgresql/data/pgdata
    networks:
        - webstack

networks:
  webstack:
    driver: bridge