version: '2'

services:
  # Reverse proxy
  reverse_proxy:
    image: jwilder/nginx-proxy:latest
    ports:
        - "80:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"

  checkfood:
    build: .
    ports:
      - "8000:80"
    environment:
      VIRTUAL_HOST: checkfood.dev
      DATABASE_DBNAME: checkfood
      DATABASE_USER: checkfood
      DATABASE_PASSWORD: checkfood
      DATABASE_HOST: db
      DATABASE_DRIVER: pdo_pgsql
    volumes:
      - .:/var/www
    links:
      - db

  db:
    image: postgres:alpine
    ports:
        - "5432:5432"
    environment:
        POSTGRES_PASSWORD: checkfood
        POSTGRES_USER: checkfood
        POSTGRES_DB: checkfood
